spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/weather
    username: postgres
    password: 123456

config:
  urlOpenWeather: https://api.openweathermap.org/data/2.5/weather
  tokenOWA: 5b9bcf19850e94e87b31de74b84b79cf
  urlYandexWeather: https://api.weather.yandex.ru/v2/informers
  tokenYandexWeather: f4d203f8-5dae-4a42-bbe2-7544f176e20c